Ecommerce/Areas/Admin/Controllers/BrandController.cs
using Ecommerce.DataAccess.Repository.IRepository;
using Ecommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Utilities;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Brand? brand = new ();
            if (id == null)
            {
                brand.Status = true;
                return View(brand);
            }

            brand = await _unitOfWork.Brand.Get(id.GetValueOrDefault());
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var allBrands = await _unitOfWork.Brand.GetAll();
            return Json(new { data = allBrands });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Brand brand)
        {
            if (ModelState.IsValid)
            {
                if (brand.Id == 0)
                {
                    await _unitOfWork.Brand.Add(brand);
                    TempData[StaticDefinitions.Success] = "Brand added successfully";
                }
                else
                {
                    _unitOfWork.Brand.Update(brand);
                    TempData[StaticDefinitions.Success] = "Brand updated successfully";
                }
                await _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[StaticDefinitions.Error] = "Error";
            return View(brand);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var brand = await _unitOfWork.Brand.Get(id);
            if (brand == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Brand.Remove(brand);
            await _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
        {
            bool value = false;
            var brand = await _unitOfWork.Brand.GetAll();

            if(id == 0)
            {
                value = brand.Any(x => x.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = brand.Any(x => x.Name.ToLower().Trim() == name.ToLower().Trim() && x.Id != id);
            }

            if(value)
            {
                return Json(new { data = true });
            }

            return Json(new { data = false });
        }
        #endregion
    }
}

Ecommerce/Areas/Admin/Controllers/CategoryController.cs
using Ecommerce.DataAccess.Repository.IRepository;
using Ecommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Utilities;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Category? category = new ();
            if (id == null)
            {
                category.Status = true;
                return View(category);
            }

            category = await _unitOfWork.Category.Get(id.GetValueOrDefault());
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var allCategories = await _unitOfWork.Category.GetAll();
            return Json(new { data = allCategories });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0)
                {
                    await _unitOfWork.Category.Add(category);
                    TempData[StaticDefinitions.Success] = "Category added successfully";
                }
                else
                {
                    _unitOfWork.Category.Update(category);
                    TempData[StaticDefinitions.Success] = "Category updated successfully";
                }
                await _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[StaticDefinitions.Error] = "Error";
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _unitOfWork.Category.Get(id);
            if (category == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Category.Remove(category);
            await _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
        {
            bool value = false;
            var categories = await _unitOfWork.Category.GetAll();

            if(id == 0)
            {
                value = categories.Any(x => x.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = categories.Any(x => x.Name.ToLower().Trim() == name.ToLower().Trim() && x.Id != id);
            }

            if(value)
            {
                return Json(new { data = true });
            }

            return Json(new { data = false });
        }
        #endregion
    }
}

Ecommerce/Areas/Admin/Controllers/StorageController.cs
using Ecommerce.DataAccess.Repository.IRepository;
using Ecommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Utilities;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StorageController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public StorageController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Storage? storage = new ();
            if (id == null)
            {
                storage.Status = true;
                return View(storage);
            }

            storage = await _unitOfWork.Storage.Get(id.GetValueOrDefault());
            if (storage == null)
            {
                return NotFound();
            }
            return View(storage);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var allStorages = await _unitOfWork.Storage.GetAll();
            return Json(new { data = allStorages });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Storage storage)
        {
            if (ModelState.IsValid)
            {
                if (storage.Id == 0)
                {
                    await _unitOfWork.Storage.Add(storage);
                    TempData[StaticDefinitions.Success] = "Storage added successfully";
                }
                else
                {
                    _unitOfWork.Storage.Update(storage);
                    TempData[StaticDefinitions.Success] = "Storage updated successfully";
                }
                await _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[StaticDefinitions.Error] = "Error";
            return View(storage);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var storage = await _unitOfWork.Storage.Get(id);
            if (storage == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Storage.Remove(storage);
            await _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
        {
            bool value = false;
            var storages = await _unitOfWork.Storage.GetAll();

            if(id == 0)
            {
                value = storages.Any(x => x.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = storages.Any(x => x.Name.ToLower().Trim() == name.ToLower().Trim() && x.Id != id);
            }

            if(value)
            {
                return Json(new { data = true });
            }

            return Json(new { data = false });
        }
        #endregion
    }
}

Ecommerce/Views/Shared/_CreateAndReturnButtons.cshtml
<div class="d-grid gap-2 d-md-block">
    <button class="btn btn-primary" onfocus="false" type="submit">
        <i class="bi bi-plus-square-fill"></i>
        Create
    </button>
    <a asp-action="Index" class="btn btn-success">
        <i class="bi bi-arrow-return-left"></i>
        Return
    </a>
</div>

Ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle  text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                Content
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Storage" asp-action="Index">Storage</a></li>
                                <li><a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a></li>
                                <li><a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a></li>
                            </ul>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ecommerce/Views/Shared/_Notifications.cshtml
@using Utilities

@if(TempData[StaticDefinitions.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData[StaticDefinitions.Success]');
    </script>
}

@if (TempData[StaticDefinitions.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData[StaticDefinitions.Error]');
    </script>
}

Ecommerce/Views/Shared/_UpdateAndReturnButtons.cshtml
@model int

<div class="d-grid gap-2 d-md-block">
    <button class="btn btn-primary" onfocus="false" type="submit" asp-route-id="@Model">
        <i class="bi bi-pencil-square"></i>
        Save Changes
    </button>
    <a asp-action="Index" class="btn btn-success">
        <i class="bi bi-arrow-return-left"></i>
        Return
    </a>
</div>